### ISSUE TITLE
error

### ISSUE THREAD

**Issue by devinssuh** [couchbaselabs/touchbase#4]
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/Users/devinsuh/Documents/tester/touchbase/TouchbaseModular/app.js:16:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)

**Comment by devinssuh** [comment]
I'm getting this error. Do i have to generate my own certs? because I did that and it was running but now it won't let me go past the sign up screen

**Comment by devinssuh** [comment]
this is what I used
http://stackoverflow.com/questions/12871565/how-to-create-pem-files-for-https-web-server

**Comment by devinssuh** [comment]
![image](https://cloud.githubusercontent.com/assets/13263661/12399503/6ce34f46-bde8-11e5-937d-4f26cbbca873.png)

It won't let me sign up

**Comment by pranavmayuram** [comment]
Were you able to do it simply over HTTP?

**Comment by devinssuh** [comment]
yep

**Comment by devinssuh** [comment]
But it won't let me sign up

**Comment by devinssuh** [comment]
how did you do it

**Comment by pranavmayuram** [comment]
I personally didn't do HTTPS. I used a GoDaddy cert and key, but I was unable to get Node to read the key and cert properly; self-signed cert was the only one I was able to use.
Were you able to sign up when you went over HTTP?

**Comment by devinssuh** [comment]
oh nvm it was self signed. even then it's not working for me. I can't even
get it working with the sign up

**Comment by pranavmayuram** [comment]
Was running it in http was completely fine? Were you able to sign up then?
If not, check your logs when using the project in HTTP, and let me know what issues you get then.
Have you set up your Couchbase node and buckets as specified in the <a href="https://github.com/couchbaselabs/touchbase/blob/master/README.md">README</a> under **Bucket Setup**?
I haven't had much success running the project with HTTPS, other than when I used self-signed certs (kind of useless), so I can't be of much assistance if the issue is solely with HTTPS. 
If you create a self-signed cert, put the "key.pem" and "cert.pem" in the same directory level as "app.js", and it should work.
